// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  plateWidth: 480,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "c2cea6f1"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "9e86b1e9"
  },
  "veiled_hollow": {
    "w": 480,
    "h": 720,
    "rowHash": "6de5b0ae"
  },
  "drakelands": {
    "w": 480,
    "h": 800,
    "rowHash": "d7912be5"
  },
  "frostveil": {
    "w": 480,
    "h": 693,
    "rowHash": "ca34af23"
  },
  "amberfall": {
    "w": 480,
    "h": 747,
    "rowHash": "5bcd3f43"
  },
  "willowfen": {
    "w": 480,
    "h": 693,
    "rowHash": "b5dbb642"
  },
  "nightbloom": {
    "w": 480,
    "h": 747,
    "rowHash": "e6dfe4ab"
  },
  "wraithwood": {
    "w": 480,
    "h": 747,
    "rowHash": "a13521d7"
  },
  "palmreach": {
    "w": 480,
    "h": 747,
    "rowHash": "a474c73f"
  },
  "evergarden": {
    "w": 480,
    "h": 747,
    "rowHash": "9d91ad28"
  },
  "galecrest": {
    "w": 480,
    "h": 693,
    "rowHash": "843854a0"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "e0be782a"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "6008eb5a"
  }
},
} as const;
