// GENERATED by scripts/vfx/gen_ingame_specs.mjs — do not hand-edit.
// Per-ability VFX specs for the in-game slice (classes: shaman).
// Source of truth: /ability_specs.js + /ability_catalog.js (the gallery data).

export interface AbilityVfxSpec {
  archetype: string;
  palette?: string;
  power?: number;
  windup?: number;
  windupStyle?: string;
  linger?: number;
  self?: boolean;
  finisher?: boolean;
  accent?: string;
  hot?: number;
  tint?: string;
  rim?: string;
  decal?: string;
  motifs?: string[];
  motifAt?: string;
  shaft?: number | boolean;
  screenFx?: boolean;
  barrier?: boolean;
  bolt?: { speed?: number; jagged?: boolean; coils?: boolean; forkEvery?: number; volley?: number; tracer?: boolean; leader?: boolean; style?: string; headScale?: number };
  strike?: { arc?: string; swings?: number; bleed?: boolean; stars?: boolean; groundSlam?: boolean };
  nova?: { radius?: number };
  beam?: { dur?: number; ticks?: number; drain?: boolean };
  dot?: { drip?: string };
  cc?: { style?: string };
  shout?: { radius?: number; target?: boolean };
  burst?: { style?: string };
  buff?: { style?: string; orbit?: string; shellDur?: number; o?: Record<string, number | string> };
  impact?: Record<string, unknown>;
  spirit?: { model?: string; path?: string; at?: string; scale?: number; dur?: number; tint?: string; dim?: number } | null;
}

export const SLICE_ABILITY_IDS: ReadonlySet<string> = new Set(["lightning_bolt","rockbiter_weapon","healing_wave","earth_shock","lightning_shield","flame_shock","flametongue_weapon","frost_shock","frostbrand_weapon","ghost_wolf","earthquake","chain_heal","stormstrike","elemental_mastery","healing_stream","chain_lightning","earthbind","bloodlust"]);

export const ABILITY_VFX_SPECS: Readonly<Record<string, AbilityVfxSpec>> = {
 "lightning_bolt": {
  "archetype": "bolt",
  "palette": "storm",
  "windup": 1.7,
  "power": 1.25,
  "windupStyle": "runes",
  "bolt": {
   "speed": 30,
   "jagged": true,
   "coils": true,
   "forkEvery": 0.09,
   "leader": true
  },
  "linger": 3.2,
  "finisher": true
 },
 "rockbiter_weapon": {
  "archetype": "buff",
  "palette": "physical",
  "power": 0.75,
  "buff": {
   "style": "raise",
   "shellDur": 1.2,
   "orbit": "weaponGlow",
   "o": {
    "rate": 0.5,
    "tickEvery": 6
   }
  },
  "linger": 2.5,
  "windup": 0.5,
  "windupStyle": "weapon",
  "rim": "#b08850",
  "decal": "crack",
  "impact": {
   "ring": 1.2,
   "debris": true,
   "sparks": 6,
   "flipbook": false,
   "vRing": false
  },
  "tint": "#c8905a"
 },
 "healing_wave": {
  "archetype": "heal",
  "palette": "frost",
  "power": 0.9,
  "windupStyle": "ascend",
  "motifs": [
   "fountain"
  ],
  "shaft": 0.65,
  "impact": {
   "vRing": 1.2,
   "light": 1.2,
   "sparks": 10,
   "flipbook": false,
   "ring": false
  }
 },
 "earth_shock": {
  "archetype": "burst",
  "palette": "physical",
  "power": 1.05,
  "burst": {
   "style": "ground"
  },
  "windup": 0.4,
  "windupStyle": "stance",
  "motifs": [
   "fissure"
  ],
  "impact": {
   "flipbook": false,
   "ring": 1.3,
   "vRing": false,
   "sparks": 8,
   "debris": true,
   "smoke": true,
   "light": 0.7
  },
  "decal": "crack",
  "tint": "#c8905a"
 },
 "lightning_shield": {
  "archetype": "buff",
  "palette": "storm",
  "power": 0.65,
  "buff": {
   "style": "raise",
   "shellDur": 1.4,
   "orbit": "sparks",
   "o": {
    "n": 3,
    "size": 0.45,
    "tex": "star",
    "rate": 1.9,
    "weave": 0.3,
    "incline": 0.35,
    "tickEvery": 2
   }
  },
  "linger": 4,
  "windup": 0.4,
  "windupStyle": "orb",
  "rim": "#7fd6ff",
  "decal": "rune"
 },
 "flame_shock": {
  "archetype": "dot",
  "palette": "fire",
  "power": 0.9,
  "dot": {
   "drip": "rise"
  },
  "linger": 4,
  "windupStyle": "none",
  "impact": {
   "ring": false,
   "vRing": false,
   "smoke": true,
   "sparks": 18,
   "flipbook": true,
   "light": 0.8
  },
  "decal": "scorch"
 },
 "flametongue_weapon": {
  "archetype": "buff",
  "palette": "fire",
  "power": 0.75,
  "buff": {
   "style": "raise",
   "shellDur": 0.9,
   "orbit": "weaponGlow",
   "o": {
    "rate": 1.8,
    "tickEvery": 2.5
   }
  },
  "linger": 3,
  "windupStyle": "none",
  "rim": "#ff8c3a",
  "decal": "scorch",
  "hot": 0.15,
  "impact": {
   "flipbook": true,
   "ring": false,
   "vRing": false,
   "sparks": 16,
   "debris": false,
   "smoke": true,
   "light": 1.3
  }
 },
 "frost_shock": {
  "archetype": "burst",
  "palette": "frost",
  "power": 0.9,
  "burst": {
   "style": "link"
  },
  "linger": 2.5,
  "windupStyle": "none",
  "impact": {
   "flipbook": false,
   "sparks": 0,
   "debris": true,
   "vRing": 1.3,
   "ring": false,
   "smoke": false,
   "light": 0.75
  },
  "screenFx": false,
  "decal": "crack"
 },
 "frostbrand_weapon": {
  "archetype": "buff",
  "palette": "frost",
  "power": 0.75,
  "buff": {
   "style": "raise",
   "shellDur": 1.6,
   "orbit": "weaponGlow",
   "o": {
    "rate": 0.8,
    "tickEvery": 4.5
   }
  },
  "linger": 3,
  "windup": 0.55,
  "windupStyle": "orb",
  "rim": "#4f9fd8",
  "impact": {
   "flipbook": false,
   "ring": false,
   "vRing": 1.1,
   "sparks": 0,
   "debris": true,
   "smoke": false,
   "light": 0.9
  }
 },
 "ghost_wolf": {
  "archetype": "buff",
  "palette": "moon",
  "power": 0.6,
  "buff": {
   "style": "morph",
   "shellDur": 1,
   "orbit": "speedlines",
   "o": {
    "rate": 1.3,
    "tickEvery": 3.5
   }
  },
  "linger": 2,
  "windupStyle": "vortex",
  "rim": "#b4a8e0",
  "spirit": {
   "model": "wolf",
   "path": "circle",
   "at": "caster",
   "scale": 0.9,
   "dur": 2.2,
   "tint": "#8fc8ff",
   "dim": 0.55
  }
 },
 "earthquake": {
  "archetype": "nova",
  "palette": "physical",
  "power": 1.3,
  "nova": {
   "radius": 8
  },
  "motifs": [
   "fissure",
   "pillars"
  ],
  "motifAt": "target",
  "linger": 6,
  "windup": 0.7,
  "windupStyle": "stance",
  "decal": "crack",
  "tint": "#c8905a",
  "screenFx": true,
  "impact": {
   "flipbook": false,
   "ring": 2,
   "vRing": false,
   "sparks": 6,
   "debris": true,
   "smoke": true,
   "light": 0.5
  }
 },
 "chain_heal": {
  "archetype": "heal",
  "palette": "frost",
  "power": 1.35,
  "windup": 2.4,
  "windupStyle": "ascend",
  "motifs": [
   "chains"
  ],
  "motifAt": "target",
  "shaft": 0.7,
  "linger": 2.6,
  "rim": "#aee7ff",
  "accent": "#cdefff",
  "impact": {
   "flipbook": false,
   "ring": false,
   "vRing": 1.2,
   "sparks": 12,
   "debris": false,
   "smoke": false,
   "light": 1.35
  }
 },
 "stormstrike": {
  "archetype": "strike",
  "palette": "storm",
  "power": 1.3,
  "strike": {
   "swings": 2,
   "arc": "vertical",
   "groundSlam": true,
   "stars": false
  },
  "windup": 0.45,
  "windupStyle": "weapon",
  "motifs": [
   "bladestorm"
  ],
  "impact": {
   "sparks": 48,
   "debris": true,
   "flipbook": true,
   "ring": false,
   "vRing": true,
   "smoke": false,
   "trail": "x",
   "light": 1.5
  },
  "decal": "crack",
  "rim": "#8fd6ff"
 },
 "elemental_mastery": {
  "archetype": "buff",
  "palette": "storm",
  "power": 1.1,
  "self": true,
  "buff": {
   "style": "raise",
   "shellDur": 1.8,
   "orbit": "halo",
   "o": {
    "n": 4,
    "size": 0.4,
    "tex": "star",
    "rate": 2,
    "weave": 0.25,
    "radius": 0.5,
    "incline": 0.02,
    "tickEvery": 2
   }
  },
  "linger": 3,
  "windup": 0.6,
  "windupStyle": "vortex",
  "rim": "#a8e6ff",
  "impact": {
   "flipbook": true,
   "ring": false,
   "vRing": true,
   "sparks": 26,
   "debris": false,
   "smoke": false,
   "light": 1.6
  }
 },
 "healing_stream": {
  "archetype": "heal",
  "palette": "nature",
  "power": 0.8,
  "accent": "#aee7ff",
  "windupStyle": "none",
  "shaft": 0.5,
  "motifs": [
   "fountain"
  ],
  "motifAt": "target",
  "linger": 4,
  "rim": "#9fd8c8",
  "impact": {
   "sparks": 6,
   "ring": false,
   "vRing": false,
   "flipbook": false,
   "debris": false,
   "smoke": false,
   "light": 1.3,
   "liteAudio": true
  }
 },
 "chain_lightning": {
  "archetype": "burst",
  "palette": "storm",
  "power": 1.25,
  "burst": {
   "style": "skybeam"
  },
  "windup": 2.2,
  "windupStyle": "vortex",
  "linger": 2,
  "rim": "#9fd0ff",
  "impact": {
   "flipbook": false,
   "ring": 1.6,
   "vRing": false,
   "sparks": 34,
   "debris": false,
   "smoke": false,
   "light": 1.3
  }
 },
 "earthbind": {
  "archetype": "nova",
  "palette": "nature",
  "power": 1,
  "nova": {
   "radius": 8
  },
  "windup": 0.3,
  "windupStyle": "stance",
  "motifs": [
   "vines"
  ],
  "motifAt": "caster",
  "decal": "crack",
  "linger": 2.5,
  "rim": "#b89a6a",
  "impact": {
   "ring": 1.8,
   "debris": true,
   "sparks": 8,
   "vRing": false,
   "flipbook": false,
   "smoke": false,
   "light": 0.7,
   "liteAudio": true
  }
 },
 "bloodlust": {
  "archetype": "buff",
  "palette": "storm",
  "power": 1.3,
  "buff": {
   "style": "raise",
   "orbit": "heartbeat",
   "shellDur": 2.5,
   "o": {
    "bpm": 160,
    "ringR": 2,
    "tickEvery": 0.6
   }
  },
  "windupStyle": "none",
  "linger": 4,
  "rim": "#8fd0ff",
  "impact": {
   "ring": 2.6,
   "vRing": true,
   "sparks": 24,
   "flipbook": false,
   "debris": false,
   "smoke": false,
   "light": 2.2,
   "sample": "imp_bloodlust"
  }
 }
};

// English aura name → slice ability id (buff-spec abilities only). Sim aura
// events name auras by ability name; sim output is locale-independent.
export const AURA_NAME_TO_ID: Readonly<Record<string, string>> = {
 "Stonebound Weapon": "rockbiter_weapon",
 "Thunder Ward": "lightning_shield",
 "Pyrebrand Weapon": "flametongue_weapon",
 "Rimebound Weapon": "frostbrand_weapon",
 "Shadewolf": "ghost_wolf",
 "Primal Mastery": "elemental_mastery",
 "Storm Chorus": "bloodlust"
};
