// Scorching Wastes — a custom-map endgame desert zone (billed 20-30; mobs run
// level 19-24 against the level-20 cap, so the back half plays as hard elite
// content). South-east beyond Thornpeak's rim, the land the first sealing of
// Korzul the Gravewyrm drank dry. Zar'Keth, the Sunken Crown — a sun-court
// city older than Eastbrook — bound a shard of the Wyrm's own fire (the First
// Ember) to relight their dying kingdom; it burned the city to glass in one
// night. Only the Heartspring still runs, fed by veins that pass beneath the
// Wyrm's prison. Now the Ashen Court keeps a dead king's protocol in the
// ruins, the Emberveil (a Wyrmcult splinter) digs for the Ember to carry it
// home and burn the Sanctum seal open, and a caravan out of Highwatch has
// raised the Last Well beside the spring to stop them.
//
// This module is data-only and base-world-safe: its NPCs are registered
// `dynamic: true` (never surface-spawned in the base world; the custom map's
// content.npcs carries the live copies at real coordinates), and its ground
// objects register with EMPTY position lists (the map document places the
// real sparkles). Mobs/items/quests ride the normal merged registries so the
// custom map's camps and quest chain resolve.

import type { GroundObjectDef, ItemDef, MobTemplate, NpcDef, QuestDef } from '../types';

// ---------------------------------------------------------------------------
// Mobs
// ---------------------------------------------------------------------------

export const SCORCHING_MOBS: Record<string, MobTemplate> = {
  // Tawny pack-cats that shadow the caravan road at dusk. The Wastes' wolves.
  duskmane_prowler: {
    id: 'duskmane_prowler',
    name: 'Duskmane Prowler',
    minLevel: 19,
    maxLevel: 20,
    family: 'beast',
    hpBase: 62,
    hpPerLevel: 22,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 1.9,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 11,
    // Sun-cracked claws leave a raking physical wound, sister to the Ridge
    // Stalker's Rending Claws.
    bleed: {
      chance: 0.25,
      perTick: 6,
      interval: 3,
      duration: 9,
      name: 'Duskmane Rake',
      school: 'physical',
    },
    loot: [
      { copper: 95, chance: 1 },
      { itemId: 'duskmane_pelt', chance: 0.6, questId: 'q_sw_prowlers' },
      { itemId: 'prowler_fang', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xc2954f,
    componentTags: ['hide', 'fang'],
  },
  // Glass-shelled scarabs that chew the vitrified ground of the old burn.
  glasscarab: {
    id: 'glasscarab',
    name: 'Glasscarab',
    minLevel: 19,
    maxLevel: 20,
    family: 'burrower',
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.1,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 10,
    // A carapace of fused glass: shrugging plates that harden mid-fight.
    stoneskin: { amount: 120, every: 16, duration: 6, name: 'Vitric Shell', school: 'physical' },
    loot: [
      { copper: 85, chance: 1 },
      { itemId: 'glasscarab_shell', chance: 0.65, questId: 'q_sw_carrion_glass' },
      { itemId: 'sunglass_shard', chance: 0.25 },
    ],
    scale: 0.9,
    color: 0x9fd8c8,
    componentTags: ['claw'],
  },
  // Waterless men are dangerous men: the Duneblades tax every skin of water
  // that crosses the flats, and the caravan's wagons were the richest take yet.
  duneblade_marauder: {
    id: 'duneblade_marauder',
    name: 'Duneblade Marauder',
    minLevel: 20,
    maxLevel: 21,
    family: 'humanoid',
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    // A pommel-crack to the jaw: the marauder's opener leaves the guard split.
    expose: { chance: 0.25, dmgIncrease: 0.18, duration: 8, name: 'Split Guard' },
    loot: [
      { copper: 110, chance: 1 },
      { itemId: 'stolen_waterskin', chance: 0.55, questId: 'q_sw_marauders' },
      { itemId: 'duneblade_token', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xa8763e,
  },
  // Karesh drank the deep cistern dry and salted what was left so no rival
  // band could follow. His men call him the Parched because nothing slakes him.
  karesh_the_parched: {
    id: 'karesh_the_parched',
    name: 'Karesh the Parched',
    minLevel: 21,
    maxLevel: 21,
    family: 'humanoid',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 24,
    hpBase: 300,
    hpPerLevel: 46,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.1,
    armorPerLevel: 26,
    moveSpeed: 7.5,
    aggroRadius: 12,
    // Every landed cut feeds the thirst — an escalating frenzy that only
    // burning him down or breaking melee resets.
    rampage: { ap: 9, maxStacks: 8, duration: 10, name: 'Parched Fury', school: 'physical' },
    // Once, when the fight turns, he upends a stolen skin over his cracked
    // lips and comes back meaner.
    desperateHeal: { belowHpPct: 0.35, healPct: 0.3 },
    loot: [
      { copper: 550, chance: 1 },
      { itemId: 'kareshs_last_skin', chance: 1, questId: 'q_sw_karesh' },
      { itemId: 'parched_kings_goblet', chance: 1 },
    ],
    yells: {
      engage: 'The dunes drink you today, wellborn!',
      enrage: 'THIRSTY. So... THIRSTY!',
    },
    scale: 1.15,
    color: 0x8f5a2b,
  },
  // The stone wardens the Sun-Court set to watch its mesa vigil. They wake
  // only when the obelisk rite is worked out of order — or finished.
  vigil_sentinel: {
    id: 'vigil_sentinel',
    name: 'Vigil Sentinel',
    minLevel: 21,
    maxLevel: 21,
    family: 'elemental',
    elite: true,
    ccImmune: true,
    respawnMult: 10,
    hpBase: 240,
    hpPerLevel: 40,
    dmgBase: 15,
    dmgPerLevel: 3.2,
    attackSpeed: 2.4,
    armorPerLevel: 34,
    moveSpeed: 6,
    aggroRadius: 12,
    stoneskin: { amount: 200, every: 15, duration: 8, name: 'Mesa Bulwark', school: 'physical' },
    knockback: { chance: 0.25, distance: 6, name: 'Sweeping Verdict' },
    loot: [
      { copper: 420, chance: 1 },
      { itemId: 'sentinel_core_stone', chance: 1 },
    ],
    scale: 1.35,
    color: 0xcbb287,
  },
  // The Sunken Crown's soldiery, still at their posts two ages after the
  // glass-fire, armor fused to bone and orders fused to habit.
  sunbaked_revenant: {
    id: 'sunbaked_revenant',
    name: 'Sunbaked Revenant',
    minLevel: 21,
    maxLevel: 22,
    family: 'undead',
    hpBase: 66,
    hpPerLevel: 23,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.3,
    armorPerLevel: 22,
    moveSpeed: 6.5,
    aggroRadius: 12,
    expose: { chance: 0.25, dmgIncrease: 0.18, duration: 8, name: 'Rusted Edge' },
    loot: [
      { copper: 120, chance: 1 },
      { itemId: 'crown_guard_seal', chance: 0.55, questId: 'q_sw_revenants' },
      { itemId: 'sunbleached_bone', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xd9c9a3,
  },
  // The court that would not die: chamberlains and lectors of Zar'Keth who
  // keep a dead protocol, reading psalms to a throne of slag.
  ashen_courtier: {
    id: 'ashen_courtier',
    name: 'Ashen Courtier',
    minLevel: 22,
    maxLevel: 23,
    family: 'undead',
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 14,
    dmgPerLevel: 3.0,
    attackSpeed: 2.0,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    manaBurn: { chance: 0.3, amount: 90, name: 'Tithe of Ash', school: 'shadow' },
    // Court manners: the lector's censure claws at the mind and dims the wit.
    enfeeble: { chance: 0.3, int: 14, duration: 12, name: 'Sunken Censure', school: 'shadow' },
    loot: [
      { copper: 140, chance: 1 },
      { itemId: 'ashen_psalter', chance: 0.5, questId: 'q_sw_courtiers' },
      { itemId: 'sunbleached_bone', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xb9a8c9,
  },
  // Voice of the dead court. Atharis crowned nine kings of Zar'Keth and means
  // to crown a tenth: the fire that unmade them all.
  sunspeaker_atharis: {
    id: 'sunspeaker_atharis',
    name: 'Sunspeaker Atharis',
    minLevel: 23,
    maxLevel: 23,
    family: 'undead',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 30,
    hpBase: 420,
    hpPerLevel: 70,
    dmgBase: 19,
    dmgPerLevel: 4.2,
    attackSpeed: 2.3,
    armorPerLevel: 38,
    moveSpeed: 6.5,
    aggroRadius: 13,
    aoePulse: { min: 26, max: 38, radius: 11, every: 9, name: 'Ash Litany', school: 'shadow' },
    bigCast: {
      castId: 'sunspeaker_coronation',
      name: 'Coronation of Cinders',
      castTime: 3,
      every: 22,
      radius: 13,
      min: 48,
      max: 66,
      school: 'fire',
      yell: 'Kneel for the crowning of the tenth king!',
    },
    summonAdds: { mobId: 'ashen_courtier', count: 2, atHpPct: [0.66, 0.33] },
    yells: {
      engage: 'The court receives no petitioners. Only tithes.',
      summon: 'Attend me, honored dead!',
    },
    loot: [
      { copper: 700, chance: 1 },
      { itemId: 'sunspeakers_ash_crown', chance: 1 },
      { itemId: 'vestment_of_the_sunken_crown', chance: 0.3 },
    ],
    scale: 1.25,
    color: 0xe8d59a,
  },
  // Wyrmcult splinter, come over the pass for the First Ember. Their veils
  // are soaked in cinder-oil; their prayers are written in scorch.
  emberveil_zealot: {
    id: 'emberveil_zealot',
    name: 'Emberveil Zealot',
    minLevel: 21,
    maxLevel: 22,
    family: 'humanoid',
    hpBase: 64,
    hpPerLevel: 22,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    // The cult hoards their master's flame: a branding strike that seals away
    // the victim's fire magic, mirroring the Wyrmward Sigil of the mother cult.
    lockout: { chance: 0.25, duration: 6, name: 'Emberward Brand', school: 'fire' },
    loot: [
      { copper: 130, chance: 1 },
      { itemId: 'emberveil_writ', chance: 0.5, questId: 'q_sw_writs' },
      { itemId: 'cinder_soaked_veil', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xb3452c,
  },
  emberveil_pyromancer: {
    id: 'emberveil_pyromancer',
    name: 'Emberveil Pyromancer',
    minLevel: 22,
    maxLevel: 23,
    family: 'humanoid',
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 14,
    dmgPerLevel: 3.1,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 11,
    // Emberbrand: the pyromancer's touch leaves the victim kindled, so every
    // spell that follows bites deeper.
    spellVuln: { chance: 0.3, amp: 0.18, duration: 10, name: 'Emberbrand', school: 'fire' },
    manaBurn: { chance: 0.25, amount: 80, name: 'Cinder Sip', school: 'fire' },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'emberveil_writ', chance: 0.5, questId: 'q_sw_writs' },
      { itemId: 'cinder_soaked_veil', chance: 0.3 },
    ],
    scale: 1.0,
    color: 0xd1502e,
  },
  // Living heat that walked out of the glass the night the city burned.
  cinder_elemental: {
    id: 'cinder_elemental',
    name: 'Cinder Elemental',
    minLevel: 22,
    maxLevel: 23,
    family: 'elemental',
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 14,
    dmgPerLevel: 3.0,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 6.5,
    aggroRadius: 11,
    spellVuln: { chance: 0.3, amp: 0.18, duration: 10, name: 'Kindling Touch', school: 'fire' },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'living_cinder', chance: 0.55, questId: 'q_sw_glasscut' },
      { itemId: 'sunglass_shard', chance: 0.35 },
    ],
    scale: 1.1,
    color: 0xe06a2b,
  },
  // A slag-hearted giant that patrols the Glasscut's crater, a coal the size
  // of a watchtower that never quite went out.
  moltenheart_colossus: {
    id: 'moltenheart_colossus',
    name: 'Moltenheart Colossus',
    minLevel: 23,
    maxLevel: 23,
    family: 'elemental',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 40,
    hpBase: 460,
    hpPerLevel: 76,
    dmgBase: 20,
    dmgPerLevel: 4.6,
    attackSpeed: 2.5,
    armorPerLevel: 42,
    moveSpeed: 6,
    aggroRadius: 13,
    aoePulse: { min: 30, max: 42, radius: 11, every: 9, name: 'Slagwave', school: 'fire' },
    enrage: { belowHpPct: 0.3, dmgMult: 1.35, hasteMult: 1.15 },
    loot: [
      { copper: 650, chance: 1 },
      { itemId: 'moltenheart_slagcore', chance: 1 },
      { itemId: 'moltenheart_girdle', chance: 0.35 },
    ],
    scale: 1.5,
    color: 0xff5a1f,
  },
  // Sparks shed by the First Ember when it stirs; they live minutes and burn
  // like grudges. Kept cheap on XP so add-waves can't be farmed.
  cinder_wisp: {
    id: 'cinder_wisp',
    name: 'Cinder Wisp',
    minLevel: 20,
    maxLevel: 20,
    family: 'elemental',
    hpBase: 30,
    hpPerLevel: 12,
    dmgBase: 10,
    dmgPerLevel: 2.4,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 8,
    aggroRadius: 10,
    xpMult: 0.4,
    loot: [],
    scale: 0.7,
    color: 0xffa14a,
  },
  // The First Ember itself: a shard of Korzul's fire the Sun-Court chained
  // into a crown and could not hold. Not the Wyrm — but the Wyrm's temper,
  // orphaned, wearing the memory of a king.
  ember_of_korzul: {
    id: 'ember_of_korzul',
    name: 'The First Ember',
    minLevel: 24,
    maxLevel: 24,
    family: 'dragonkin',
    boss: true,
    elite: true,
    ccImmune: true,
    respawnMult: 36,
    hpBase: 560,
    hpPerLevel: 88,
    dmgBase: 23,
    dmgPerLevel: 5.2,
    attackSpeed: 2.4,
    armorPerLevel: 46,
    moveSpeed: 6.5,
    aggroRadius: 14,
    aoePulse: { min: 34, max: 46, radius: 12, every: 10, name: 'Cinder Nova', school: 'fire' },
    bigCast: {
      castId: 'first_ember_sunflare',
      name: 'Sunflare',
      castTime: 3,
      every: 24,
      radius: 14,
      min: 56,
      max: 76,
      school: 'fire',
      yell: 'I crowned nine kings. I will wear the tenth crown MYSELF.',
    },
    summonAdds: { mobId: 'cinder_wisp', count: 3, atHpPct: [0.7, 0.4] },
    enrage: { belowHpPct: 0.25, dmgMult: 1.4, hasteMult: 1.2 },
    yells: {
      engage: 'The sun remembers this land. And I remember the sun.',
      summon: 'Rise, my sparks — the night is full of tinder!',
      enrage: 'BURN WITH ME.',
    },
    loot: [
      { copper: 900, chance: 1 },
      { itemId: 'heart_of_the_first_ember', chance: 1 },
      { itemId: 'emberglass_scepter', chance: 0.35, rollGroup: 'first_ember_chase' },
      { itemId: 'emberbound_leggings', chance: 0.3, rollGroup: 'first_ember_chase' },
    ],
    scale: 1.6,
    color: 0xff7733,
  },
};

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const SCORCHING_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  brimming_waterskin: {
    id: 'brimming_waterskin',
    name: 'Brimming Waterskin',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_arrival',
  },
  duskmane_pelt: {
    id: 'duskmane_pelt',
    name: 'Duskmane Pelt',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_prowlers',
  },
  glasscarab_shell: {
    id: 'glasscarab_shell',
    name: 'Glasscarab Shell',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_carrion_glass',
  },
  caravan_manifest: {
    id: 'caravan_manifest',
    name: 'Water-Stained Manifest',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_lost_caravan',
  },
  stolen_waterskin: {
    id: 'stolen_waterskin',
    name: 'Stolen Waterskin',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_marauders',
  },
  kareshs_last_skin: {
    id: 'kareshs_last_skin',
    name: "Karesh's Last Skin",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_karesh',
  },
  mural_rubbing: {
    id: 'mural_rubbing',
    name: 'Mural Rubbing',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_survey',
  },
  vigil_obelisk_dawn: {
    id: 'vigil_obelisk_dawn',
    name: 'Dawnfire Sigil',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_vigil_dawn',
  },
  vigil_obelisk_noon: {
    id: 'vigil_obelisk_noon',
    name: 'Noonfire Sigil',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_vigil_noon',
  },
  vigil_obelisk_dusk: {
    id: 'vigil_obelisk_dusk',
    name: 'Duskfire Sigil',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_vigil_dusk',
  },
  crown_guard_seal: {
    id: 'crown_guard_seal',
    name: 'Crown Guard Seal',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_revenants',
  },
  ashen_psalter: {
    id: 'ashen_psalter',
    name: 'Ashen Psalter',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_courtiers',
  },
  crown_brazier: {
    id: 'crown_brazier',
    name: 'Crown Brazier',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_braziers',
  },
  emberveil_writ: {
    id: 'emberveil_writ',
    name: 'Emberveil Writ',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_writs',
  },
  living_cinder: {
    id: 'living_cinder',
    name: 'Living Cinder',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_glasscut',
  },
  heartspring_offering: {
    id: 'heartspring_offering',
    name: 'Heartspring Offering Bowl',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_offering',
  },
  springheart_blessing: {
    id: 'springheart_blessing',
    name: 'Springheart Blessing',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sw_offering',
  },
  // --- treasure / flavor ---
  wastes_relic_cache: {
    id: 'wastes_relic_cache',
    name: 'Sun-Court Relic Cache',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 450,
  },
  prowler_fang: {
    id: 'prowler_fang',
    name: 'Prowler Fang',
    kind: 'junk',
    quality: 'common',
    sellValue: 60,
  },
  sunglass_shard: {
    id: 'sunglass_shard',
    name: 'Sunglass Shard',
    kind: 'junk',
    quality: 'common',
    sellValue: 90,
  },
  duneblade_token: {
    id: 'duneblade_token',
    name: 'Duneblade Token',
    kind: 'junk',
    quality: 'common',
    sellValue: 75,
  },
  sunbleached_bone: {
    id: 'sunbleached_bone',
    name: 'Sunbleached Bone',
    kind: 'junk',
    quality: 'common',
    sellValue: 70,
  },
  cinder_soaked_veil: {
    id: 'cinder_soaked_veil',
    name: 'Cinder-Soaked Veil',
    kind: 'junk',
    quality: 'common',
    sellValue: 85,
  },
  parched_kings_goblet: {
    id: 'parched_kings_goblet',
    name: "The Parched King's Goblet",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 320,
  },
  sentinel_core_stone: {
    id: 'sentinel_core_stone',
    name: 'Sentinel Core-Stone',
    kind: 'junk',
    quality: 'common',
    sellValue: 260,
  },
  sunspeakers_ash_crown: {
    id: 'sunspeakers_ash_crown',
    name: "Sunspeaker's Ash Crown",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 380,
  },
  moltenheart_slagcore: {
    id: 'moltenheart_slagcore',
    name: 'Moltenheart Slagcore',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 400,
  },
  heart_of_the_first_ember: {
    id: 'heart_of_the_first_ember',
    name: 'Heart of the First Ember',
    kind: 'junk',
    quality: 'rare',
    sellValue: 800,
  },
  // --- quest reward gear (cloth so every REWARD_ARCHETYPE class can equip) ---
  wastewalker_treads: {
    id: 'wastewalker_treads',
    name: 'Wastewalker Treads',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 54, agi: 4, sta: 3 },
    sellValue: 650,
  },
  dunewatch_sash: {
    id: 'dunewatch_sash',
    name: 'Dunewatch Sash',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 48, sta: 4, int: 3 },
    sellValue: 650,
  },
  vestment_of_the_sunken_crown: {
    id: 'vestment_of_the_sunken_crown',
    name: 'Vestment of the Sunken Crown',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 78, sta: 5, int: 5 },
    sellValue: 900,
  },
  emberbound_leggings: {
    id: 'emberbound_leggings',
    name: 'Emberbound Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'rare',
    stats: { armor: 72, sta: 6, int: 5 },
    sellValue: 950,
  },
  // --- rare-elite chase drops ---
  moltenheart_girdle: {
    id: 'moltenheart_girdle',
    name: 'Moltenheart Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'rare',
    stats: { armor: 96, sta: 6, str: 4 },
    sellValue: 850,
  },
  emberglass_scepter: {
    id: 'emberglass_scepter',
    name: 'Emberglass Scepter',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 19, max: 31, speed: 2.6 },
    stats: { int: 6, sta: 3 },
    sellValue: 950,
  },
  // --- vendor stock: Provisioner Ashka (food/water) ---
  sunbaked_flatbread: {
    id: 'sunbaked_flatbread',
    name: 'Sunbaked Flatbread',
    kind: 'food',
    quality: 'common',
    foodHp: 874,
    sellValue: 150,
    buyValue: 2500,
  },
  cactus_pressed_water: {
    id: 'cactus_pressed_water',
    name: 'Cactus-Pressed Water',
    kind: 'drink',
    quality: 'common',
    drinkMana: 900,
    sellValue: 150,
    buyValue: 2500,
  },
  lastwell_datewine: {
    id: 'lastwell_datewine',
    name: 'Last Well Datewine',
    kind: 'food',
    quality: 'common',
    foodHp: 620,
    sellValue: 90,
    buyValue: 1500,
  },
  // --- vendor stock: Forgemaster Derin (whites) ---
  duneforged_warblade: {
    id: 'duneforged_warblade',
    name: 'Duneforged Warblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 16, max: 25, speed: 2.3 },
    sellValue: 650,
    buyValue: 6500,
  },
  sunbleached_staff: {
    id: 'sunbleached_staff',
    name: 'Sunbleached Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 17, max: 28, speed: 3.0 },
    stats: { int: 2 },
    sellValue: 650,
    buyValue: 6500,
  },
  glasscut_dirk: {
    id: 'glasscut_dirk',
    name: 'Glasscut Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 11, max: 17, speed: 1.8, dagger: true },
    sellValue: 650,
    buyValue: 6500,
  },
  wastewalker_jerkin: {
    id: 'wastewalker_jerkin',
    name: 'Wastewalker Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 130 },
    sellValue: 700,
    buyValue: 7000,
  },
  caravan_guard_mail: {
    id: 'caravan_guard_mail',
    name: 'Caravan Guard Mail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 170 },
    sellValue: 750,
    buyValue: 7500,
  },
};

// ---------------------------------------------------------------------------
// NPCs — registered dynamic:true so the base world never surface-spawns them.
// The Scorching Wastes map document carries live (non-dynamic) copies of the
// same ids at their real desert coordinates; quest giver/turn-in linkage is by
// id string, so both copies resolve the same quests. Dummy positions sit in
// the Thornpeak band so zone-attribution tests file these quests as endgame.
// ---------------------------------------------------------------------------

export const SCORCHING_NPCS: Record<string, NpcDef> = {
  caravan_master_saffa: {
    id: 'caravan_master_saffa',
    name: 'Caravan-Master Saffa',
    title: 'Keeper of the Last Well',
    pos: { x: 2, z: 662 },
    facing: 0,
    color: 0xc9812f,
    dynamic: true,
    questIds: ['q_sw_arrival', 'q_sw_lost_caravan', 'q_sw_marauders', 'q_sw_afterglow'],
    greeting:
      'Water is the only coin out here, friend. Highwatch sent us to spend it well — and the Wastes mean to bankrupt us.',
  },
  scout_maren_wastes: {
    id: 'scout_maren_wastes',
    name: 'Scout Maren',
    title: "Marshal's Scout",
    pos: { x: 5, z: 660 },
    facing: 0,
    color: 0x6d8a3f,
    dynamic: true,
    questIds: ['q_sw_prowlers', 'q_sw_carrion_glass', 'q_sw_karesh'],
    greeting:
      'I tracked mud through Mirefen and snow over Thornpeak. Sand is worse. Sand remembers every step you take.',
  },
  loremaster_caddis_wastes: {
    id: 'loremaster_caddis_wastes',
    name: 'Loremaster Caddis',
    title: 'Scholar of the Sunken Crown',
    pos: { x: 8, z: 663 },
    facing: 0,
    color: 0x4f6d9c,
    dynamic: true,
    questIds: [
      'q_sw_survey',
      'q_sw_vigil_dawn',
      'q_sw_vigil_noon',
      'q_sw_vigil_dusk',
      'q_sw_revenants',
      'q_sw_courtiers',
      'q_sw_braziers',
      'q_sw_sunspeaker',
    ],
    greeting:
      "Zar'Keth fell in one night, $N — a whole kingdom, fused to glass mid-sentence. I have waited my entire life to hear the rest of that sentence.",
  },
  brother_aldric_wastes: {
    id: 'brother_aldric_wastes',
    name: 'Brother Aldric',
    title: 'Priest of the Vale',
    pos: { x: 11, z: 661 },
    facing: 0,
    color: 0xd8d0bd,
    dynamic: true,
    questIds: ['q_sw_emberveil', 'q_sw_writs', 'q_sw_glasscut', 'q_sw_first_ember'],
    greeting:
      "The Wyrm's heat bleeds even here, $N — I feel it through my boot-soles. Whatever the cult digs for in that glass, they must not carry it home.",
  },
  old_haruk: {
    id: 'old_haruk',
    name: 'Old Haruk',
    title: 'Warden of the Heartspring',
    pos: { x: 14, z: 664 },
    facing: 0,
    color: 0x7a9b8e,
    dynamic: true,
    // q_sw_first_ember is given by Brother Aldric but turned in here, at the
    // falls — the fire goes back to the water that drowned it once before.
    questIds: ['q_sw_offering', 'q_sw_first_ember'],
    greeting:
      'My family has watered this spring since before it needed watching. Nine kings drank from it. The tenth tried to drink it ALL.',
  },
  provisioner_ashka: {
    id: 'provisioner_ashka',
    name: 'Provisioner Ashka',
    title: 'Caravan Provisioner',
    pos: { x: 3, z: 667 },
    facing: 0,
    color: 0x9c6b3f,
    dynamic: true,
    questIds: [],
    vendorItems: [
      'sunbaked_flatbread',
      'cactus_pressed_water',
      'lastwell_datewine',
      'healing_potion',
      'mana_potion',
    ],
    greeting: 'Flatbread, datewine, and water with no bodies in it. Finest stock in the Wastes.',
  },
  forgemaster_derin: {
    id: 'forgemaster_derin',
    name: 'Forgemaster Derin',
    title: 'Caravan Smith',
    pos: { x: 9, z: 669 },
    facing: 0,
    color: 0x6e6e78,
    dynamic: true,
    questIds: [],
    vendorItems: [
      'duneforged_warblade',
      'sunbleached_staff',
      'glasscut_dirk',
      'wastewalker_jerkin',
      'caravan_guard_mail',
    ],
    greeting:
      'Sand in the forge, sand in the quench, sand in my teeth. The blades come out sharper for the grudge.',
  },
  // Hub flavor roster (no quests) — registered so nameplates and the online
  // client resolve their display names; live copies spawn from the map doc.
  wellwatch_hana: {
    id: 'wellwatch_hana',
    name: 'Wellwatch Hana',
    title: 'Caravan Guard',
    pos: { x: 4, z: 671 },
    facing: 0,
    color: 0x707a8c,
    dynamic: true,
    questIds: [],
    greeting: 'Walk in with water, walk out with water. Everything between is my problem.',
  },
  wellwatch_toma: {
    id: 'wellwatch_toma',
    name: 'Wellwatch Toma',
    title: 'Caravan Guard',
    pos: { x: 7, z: 673 },
    facing: 0,
    color: 0x707a8c,
    dynamic: true,
    questIds: [],
    greeting: "Quiet shift. Out here 'quiet' just means the sand is chewing slower.",
  },
  drover_pell: {
    id: 'drover_pell',
    name: 'Drover Pell',
    title: 'Mule-Drover',
    pos: { x: 10, z: 675 },
    facing: 0,
    color: 0x8a6f47,
    dynamic: true,
    questIds: [],
    greeting: 'The mules drink first. Caravan law. You want to argue law with a mule, be my guest.',
  },
  dowser_emrys: {
    id: 'dowser_emrys',
    name: 'Dowser Emrys',
    title: 'Water-Finder',
    pos: { x: 13, z: 677 },
    facing: 0,
    color: 0x5f8a9c,
    dynamic: true,
    questIds: [],
    greeting:
      'My rod bends double at the falls and nowhere else for forty miles. This land is one spring away from being a graveyard.',
  },
  auctioneer_zeph: {
    id: 'auctioneer_zeph',
    name: 'Auctioneer Zeph',
    title: 'Keeper of the World Market',
    pos: { x: 15, z: 668 },
    facing: 0,
    color: 0xb08d57,
    dynamic: true,
    questIds: [],
    market: true,
    greeting: 'The Market reaches even the Last Well, friend. Gold weighs the same in any desert.',
  },
};

// ---------------------------------------------------------------------------
// Ground objects — registered with EMPTY positions (base-world-safe). The
// custom map's content.objects places the live sparkles at real coordinates.
// ---------------------------------------------------------------------------

export const SCORCHING_OBJECTS: GroundObjectDef[] = [
  { itemId: 'brimming_waterskin', name: 'Heartspring Pool', positions: [] },
  { itemId: 'caravan_manifest', name: 'Wrecked Supply Wagon', positions: [] },
  { itemId: 'mural_rubbing', name: 'Sun-Court Mural', positions: [] },
  { itemId: 'vigil_obelisk_dawn', name: 'Obelisk of Dawn', positions: [] },
  { itemId: 'vigil_obelisk_noon', name: 'Obelisk of Noon', positions: [] },
  { itemId: 'vigil_obelisk_dusk', name: 'Obelisk of Dusk', positions: [] },
  { itemId: 'crown_brazier', name: 'Crown Brazier', positions: [] },
  { itemId: 'heartspring_offering', name: 'Heartspring Offering Bowl', positions: [] },
  { itemId: 'wastes_relic_cache', name: 'Sun-Court Relic Cache', positions: [] },
];

// ---------------------------------------------------------------------------
// Quests — four acts, level 20-30 billing (level-20 cap: XP past the cap
// feeds prestige). Ordered puzzles ride quest chains: the mural survey names
// the obelisk order, and each obelisk quest gates the next interact.
// ---------------------------------------------------------------------------

export const SCORCHING_QUESTS: Record<string, QuestDef> = {
  // --- ACT I — The Last Well ---
  q_sw_arrival: {
    id: 'q_sw_arrival',
    name: 'The Last Well',
    giverNpcId: 'caravan_master_saffa',
    turnInNpcId: 'caravan_master_saffa',
    text: 'Welcome to the end of the map, $N. Highwatch calls this venture "the southern expedition"; I call it forty souls and one spring. Before anything else — water. Draw four skins from the Heartspring pools north of camp so I know the line to the falls is safe to walk.',
    completionText:
      'Cold, clear, and no arrows in you — that is the best news the Last Well has had all season.',
    objectives: [
      { type: 'collect', itemId: 'brimming_waterskin', count: 4, label: 'Brimming Waterskin' },
    ],
    xpReward: 3400,
    copperReward: 1600,
    itemRewards: {},
    minLevel: 17,
  },
  q_sw_prowlers: {
    id: 'q_sw_prowlers',
    name: 'Teeth of the Dusk',
    giverNpcId: 'scout_maren_wastes',
    turnInNpcId: 'scout_maren_wastes',
    text: 'The duskmanes have learned the sound of our water-carts, $N. Every dusk they pace closer, and last night one dragged off a mule with the harness still on it. Thin the packs on the Bonewind Flats south of camp and bring me eight pelts as proof the lesson took.',
    completionText:
      'Eight pelts, eight fewer shadows at the picket line. The mules may finally sleep — which is more than I do.',
    objectives: [
      { type: 'kill', targetMobId: 'duskmane_prowler', count: 10, label: 'Duskmane Prowler slain' },
      { type: 'collect', itemId: 'duskmane_pelt', count: 8, label: 'Duskmane Pelt' },
    ],
    xpReward: 3800,
    copperReward: 1800,
    itemRewards: {},
    requiresQuest: 'q_sw_arrival',
    minLevel: 17,
  },
  q_sw_carrion_glass: {
    id: 'q_sw_carrion_glass',
    name: 'Carrion Glass',
    giverNpcId: 'scout_maren_wastes',
    turnInNpcId: 'scout_maren_wastes',
    text: 'Glasscarabs, the drovers call them — beetles the size of hounds with shells of fused glass, boiling out of the burn to the east. Derin swears the shells will edge a blade finer than any whetstone. Crack eight carabs and bring six unbroken shells; mind the shine, it means they are hardening.',
    completionText:
      'Look at that edge-light! Derin owes me a sharpening for life, and the east road owes you a quieter crossing.',
    objectives: [
      { type: 'kill', targetMobId: 'glasscarab', count: 8, label: 'Glasscarab slain' },
      { type: 'collect', itemId: 'glasscarab_shell', count: 6, label: 'Glasscarab Shell' },
    ],
    xpReward: 3800,
    copperReward: 1800,
    itemRewards: {},
    requiresQuest: 'q_sw_arrival',
    minLevel: 17,
  },
  q_sw_lost_caravan: {
    id: 'q_sw_lost_caravan',
    name: 'What the Dunes Kept',
    giverNpcId: 'caravan_master_saffa',
    turnInNpcId: 'caravan_master_saffa',
    text: "Three wagons never made the well, $N — grain, tools, and my sister's husband driving the lead cart. The storm scattered them across the southwest dunes. Find the wrecks and search them. I need the manifests to know what we lost... and I need to know if anyone walked away.",
    completionText:
      'Boot prints leading AWAY from the wrecks — then nothing but marauder tracks. They took the drivers alive. That is either mercy or arithmetic, and out here I know which one to bet on.',
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'caravan_manifest',
        count: 4,
        label: 'Wrecked wagon searched',
      },
    ],
    xpReward: 4000,
    copperReward: 1900,
    itemRewards: {},
    requiresQuest: 'q_sw_arrival',
    minLevel: 17,
  },
  q_sw_marauders: {
    id: 'q_sw_marauders',
    name: 'The Water Tax',
    giverNpcId: 'caravan_master_saffa',
    turnInNpcId: 'caravan_master_saffa',
    text: "The Duneblades call it a tax: your water or your blood, payable on sight. They hold a camp in the hollow southwest of the dunes, drinking our stolen skins around our stolen fires. Break them, $N. Ten marauders down, and bring back five skins — those are our people's lives in leather.",
    completionText:
      'Every skin you carry is a day someone at this well does not die. The Duneblades will remember the price of taxing us.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'duneblade_marauder',
        count: 10,
        label: 'Duneblade Marauder slain',
      },
      { type: 'collect', itemId: 'stolen_waterskin', count: 5, label: 'Stolen Waterskin' },
    ],
    xpReward: 4200,
    copperReward: 2000,
    itemRewards: {},
    requiresQuest: 'q_sw_lost_caravan',
    minLevel: 18,
  },
  q_sw_karesh: {
    id: 'q_sw_karesh',
    name: 'The Parched King',
    giverNpcId: 'scout_maren_wastes',
    turnInNpcId: 'scout_maren_wastes',
    text: "Their chief styles himself Karesh the Parched — he drank his own cistern dry and salted the dregs so no rival could follow him. A man who will do that to his own well will do worse to ours. He holds court in Karesh's Hollow under the western ridge. End his reign, $N, and bring me the last skin he is hoarding.",
    completionText:
      'So that is the last skin of the Parched King. Saffa will pour it back into the well — every drop, on principle.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'karesh_the_parched',
        count: 1,
        label: 'Karesh the Parched slain',
      },
      { type: 'collect', itemId: 'kareshs_last_skin', count: 1, label: "Karesh's Last Skin" },
    ],
    xpReward: 4600,
    copperReward: 2400,
    itemRewards: { warrior: 'dunewatch_sash', mage: 'dunewatch_sash', rogue: 'dunewatch_sash' },
    requiresQuest: 'q_sw_marauders',
    minLevel: 18,
    suggestedPlayers: 2,
  },
  // --- ACT II — The Mesa of the Vigil ---
  q_sw_survey: {
    id: 'q_sw_survey',
    name: 'The Sentence Interrupted',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "Now that the well can spare you — walk history with me, $N. The Sun-Court left murals: one under the Aqueduct Spine, one at the mesa's foot, one by the twin towers at the oasis ruin. Take rubbings of all three. Zar'Keth died mid-sentence, and I mean to read the rest of it.",
    completionText:
      'There — the sentence completes: "When the crown grew too hot to wear, the kings climbed the mesa and gave the fire BACK." A rite of renunciation, worked on obelisks — dawn, then noon, then dusk. That order matters, $N. Rites always mind their order.',
    objectives: [
      { type: 'collect', itemId: 'mural_rubbing', count: 3, label: 'Mural rubbing taken' },
    ],
    xpReward: 4200,
    copperReward: 2000,
    itemRewards: {},
    requiresQuest: 'q_sw_arrival',
    minLevel: 18,
  },
  q_sw_vigil_dawn: {
    id: 'q_sw_vigil_dawn',
    name: 'The Vigil: Dawn',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "The mesa west of camp is the Vigil itself — the kings' renunciation path. The Obelisk of Dawn stands on the first terrace, where the sun strikes first. Climb the switchbacks and lay your hand on it. Dawn wakes first; the mural is quite insistent.",
    completionText:
      'You felt it hum? Marvelous. The rite still holds its charge after two ages. Dawn is lit — noon waits above.',
    objectives: [
      {
        type: 'collect',
        itemId: 'vigil_obelisk_dawn',
        count: 1,
        label: 'Dawnfire Sigil drawn from the obelisk',
      },
    ],
    xpReward: 4200,
    copperReward: 2000,
    itemRewards: {},
    requiresQuest: 'q_sw_survey',
    minLevel: 18,
  },
  q_sw_vigil_noon: {
    id: 'q_sw_vigil_noon',
    name: 'The Vigil: Noon',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "Noon crowns the summit — the second obelisk stands at the mesa's very top, where the sun owns the whole sky. The climb is the point, $N: the kings carried their crowns up every step of it. Wake the Obelisk of Noon.",
    completionText:
      'Dawn, then noon. One hour of the rite remains — and the Vigil is beginning to notice us.',
    objectives: [
      {
        type: 'collect',
        itemId: 'vigil_obelisk_noon',
        count: 1,
        label: 'Noonfire Sigil drawn from the obelisk',
      },
    ],
    xpReward: 4400,
    copperReward: 2100,
    itemRewards: {},
    requiresQuest: 'q_sw_vigil_dawn',
    minLevel: 19,
  },
  q_sw_vigil_dusk: {
    id: 'q_sw_vigil_dusk',
    name: 'The Vigil: Dusk',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: 'Dusk is always last to the vigil — its obelisk stands on the western spur, over the canyon. But understand what the rite is, $N: a renunciation must be WITNESSED. The court set a sentinel of living mesa-stone to stand witness, and when dusk lights, it will wake to judge whether you renounce or merely take. Convince it. Thoroughly.',
    completionText:
      "The Sentinel judged you worthy — or judged you unkillable, which to a stone is the same finding. The Vigil is complete, and every door in Zar'Keth just became a question worth asking.",
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'vigil_obelisk_dusk',
        count: 1,
        label: 'Obelisk of Dusk awakened',
      },
      { type: 'kill', targetMobId: 'vigil_sentinel', count: 1, label: 'Vigil Sentinel defeated' },
    ],
    xpReward: 4800,
    copperReward: 2400,
    itemRewards: {
      warrior: 'wastewalker_treads',
      mage: 'wastewalker_treads',
      rogue: 'wastewalker_treads',
    },
    requiresQuest: 'q_sw_vigil_noon',
    minLevel: 19,
    suggestedPlayers: 2,
  },
  // --- ACT III — The Sunken Crown ---
  q_sw_revenants: {
    id: 'q_sw_revenants',
    name: 'Posts of the Dead',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "Zar'Keth's soldiery never learned the war was lost — never learned it was BRIEF. They walk the outer ruin north of the falls with their armor fused to their bones, challenging travelers for passwords no living tongue remembers. Put twelve of them to rest, $N, and gather their guard-seals; the seals will pass us deeper into the city.",
    completionText:
      'Each seal still warm — loyal to the last, and past it. Whatever holds their watch together sits further in, and now we outrank it.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'sunbaked_revenant',
        count: 12,
        label: 'Sunbaked Revenant slain',
      },
      { type: 'collect', itemId: 'crown_guard_seal', count: 6, label: 'Crown Guard Seal' },
    ],
    xpReward: 5000,
    copperReward: 2600,
    itemRewards: {},
    requiresQuest: 'q_sw_vigil_dusk',
    minLevel: 19,
  },
  q_sw_courtiers: {
    id: 'q_sw_courtiers',
    name: 'The Court of Ash',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "Deeper in, the court itself still sits — chamberlains and lectors keeping a dead king's protocol, reading psalms to a throne of slag. Their psalters hold the sanctum liturgy, and the liturgy holds the rite that lights the Crown's braziers. Break up the session, $N, and bring me a psalter with its pages intact.",
    completionText:
      "Oh, this is beautiful work — the whole brazier rite, notated in a dead cantor's hand. They kept singing it for two hundred years to an empty throne. I almost pity them. Almost.",
    objectives: [
      { type: 'kill', targetMobId: 'ashen_courtier', count: 8, label: 'Ashen Courtier slain' },
      { type: 'collect', itemId: 'ashen_psalter', count: 1, label: 'Ashen Psalter' },
    ],
    xpReward: 5200,
    copperReward: 2700,
    itemRewards: {},
    requiresQuest: 'q_sw_revenants',
    minLevel: 20,
  },
  q_sw_braziers: {
    id: 'q_sw_braziers',
    name: 'The Crown Alight',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: 'The psalter names three Crown Braziers among the towers — light all three and the inner sanctum opens itself, as it did for coronations. I have chalked the rite onto your gauntlet, $N; try not to sweat. Fair warning: a lit crown is a visible crown. Everything in that city will know the moment the third flame takes.',
    completionText:
      'From the well we watched the towers catch light one by one — Saffa wept, and I confess I lectured no one about it. The sanctum stands open. And something inside is singing back.',
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'crown_brazier',
        count: 3,
        label: 'Crown Brazier lit',
      },
    ],
    xpReward: 5400,
    copperReward: 2800,
    itemRewards: {},
    requiresQuest: 'q_sw_courtiers',
    minLevel: 20,
  },
  q_sw_sunspeaker: {
    id: 'q_sw_sunspeaker',
    name: 'The Tenth Coronation',
    giverNpcId: 'loremaster_caddis_wastes',
    turnInNpcId: 'loremaster_caddis_wastes',
    text: "The voice in the sanctum is Sunspeaker Atharis — crowner of all nine kings of Zar'Keth. The psalms name him the court's living memory, and he has spent two ages preparing a tenth coronation: for the fire itself. He stands at the Sun-Throne between the twin towers. Depose him, $N, before he finishes a rite the whole desert will regret.",
    completionText:
      "Nine crowns he set on nine brows, and the tenth would have burned the world to fit it. History will record that you adjourned the court of Zar'Keth. I will make certain history phrases it exactly that way.",
    objectives: [
      {
        type: 'kill',
        targetMobId: 'sunspeaker_atharis',
        count: 1,
        label: 'Sunspeaker Atharis deposed',
      },
    ],
    xpReward: 5800,
    copperReward: 3200,
    itemRewards: {
      warrior: 'vestment_of_the_sunken_crown',
      mage: 'vestment_of_the_sunken_crown',
      rogue: 'vestment_of_the_sunken_crown',
    },
    requiresQuest: 'q_sw_braziers',
    minLevel: 20,
    suggestedPlayers: 2,
  },
  // --- ACT IV — The First Ember ---
  q_sw_emberveil: {
    id: 'q_sw_emberveil',
    name: 'The Emberveil',
    giverNpcId: 'brother_aldric_wastes',
    turnInNpcId: 'brother_aldric_wastes',
    text: 'You have seen the veiled camps along the eastern rim, $N. They are Wyrmcult — a splinter sect, the Emberveil, come over the pass while Highwatch watched the Sanctum gates. Where the mother cult sings to wake the Wyrm, these dig to ARM it. Their zealots and pyromancers are sweeping the glass for something. Thin them before they find it.',
    completionText:
      'Sixteen fewer shovels in that glass. But the digging goes on day and night — they are not searching anymore, $N. They are excavating.',
    objectives: [
      { type: 'kill', targetMobId: 'emberveil_zealot', count: 10, label: 'Emberveil Zealot slain' },
      {
        type: 'kill',
        targetMobId: 'emberveil_pyromancer',
        count: 6,
        label: 'Emberveil Pyromancer slain',
      },
    ],
    xpReward: 5600,
    copperReward: 3000,
    itemRewards: {},
    requiresQuest: 'q_sw_sunspeaker',
    minLevel: 20,
  },
  q_sw_writs: {
    id: 'q_sw_writs',
    name: 'Writs of the Veil',
    giverNpcId: 'brother_aldric_wastes',
    turnInNpcId: 'brother_aldric_wastes',
    text: "Their leaders carry writs — orders in the mother cult's cipher. I broke that cipher at Highwatch and I will break it again here. Bring me five writs from the Emberveil, $N, and we will read exactly what they were sent to fetch.",
    completionText:
      "As I feared. \"Recover the FIRST EMBER — the shard of the Master's fire the sun-kings stole and chained. Carry it to the Sanctum gate; the seal will not suffer its own flame.\" They mean to burn the Wyrm's door open with the Wyrm's own stolen fire, $N.",
    objectives: [{ type: 'collect', itemId: 'emberveil_writ', count: 5, label: 'Emberveil Writ' }],
    xpReward: 5800,
    copperReward: 3100,
    itemRewards: {},
    requiresQuest: 'q_sw_emberveil',
    minLevel: 20,
  },
  q_sw_glasscut: {
    id: 'q_sw_glasscut',
    name: 'Where the Sky Burned',
    giverNpcId: 'brother_aldric_wastes',
    turnInNpcId: 'brother_aldric_wastes',
    text: "The Glasscut is where the First Ember fell the night it unmade Zar'Keth — the ground still runs hot, and cinder elementals walk it like sparks that never landed. The Ember is waking, $N; its sparks grow bolder as the cult digs closer. Scatter eight of them and bring me five living cinders. I must take the measure of the fire we face.",
    completionText:
      "They squirm even in blessed salt... this is dragonfire, no mistaking it now. The Ember is not a relic, $N. It is a REMNANT — a living piece of Korzul's temper, and it remembers being worn as a crown.",
    objectives: [
      { type: 'kill', targetMobId: 'cinder_elemental', count: 8, label: 'Cinder Elemental slain' },
      { type: 'collect', itemId: 'living_cinder', count: 5, label: 'Living Cinder' },
    ],
    xpReward: 6000,
    copperReward: 3300,
    itemRewards: {},
    requiresQuest: 'q_sw_writs',
    minLevel: 20,
  },
  q_sw_offering: {
    id: 'q_sw_offering',
    name: 'The Spring Remembers',
    giverNpcId: 'old_haruk',
    turnInNpcId: 'old_haruk',
    text: "The priest means to face the fire, and you with him. Then hear a well-keeper's wisdom, $N: the Heartspring rises from beneath the Wyrm's own prison, and what passes under a thing knows that thing. Take my offering bowl to the pool atop the falls, pour, and listen. The spring has drowned this fire once before. Let it bless you before you go asking to be burned.",
    completionText:
      'You heard it too — the deep water, moving under the world. Wear that sound like armor, $N. Fire is loud, but the spring was here first, and it will be here after.',
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'heartspring_offering',
        count: 1,
        label: 'Offering poured at the Heartspring',
      },
    ],
    xpReward: 5200,
    copperReward: 2500,
    itemRewards: {},
    requiresQuest: 'q_sw_glasscut',
    minLevel: 20,
  },
  q_sw_first_ember: {
    id: 'q_sw_first_ember',
    name: 'The First Ember',
    giverNpcId: 'brother_aldric_wastes',
    turnInNpcId: 'old_haruk',
    text: "It is uncovered, $N. The cult's pit broke open at dawn and the Glasscut lit from within — the First Ember stands in the crater it made two ages ago, wearing fire like a king's regalia, and the Emberveil kneel to it in rows. If it reaches the Sanctum gate, everything Highwatch bled for is ash. You carry the spring's blessing and the Vigil's witness. Go down into the glass and finish the sentence Zar'Keth began: the fire goes BACK.",
    completionText:
      'The falls ran quick and bright the moment it died — the spring, taking its old enemy under. You have done what nine kings could not, $N: you gave the fire back. Sit. Drink. The water is sweetest tonight.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'ember_of_korzul',
        count: 1,
        label: 'The First Ember extinguished',
      },
    ],
    xpReward: 6800,
    copperReward: 4200,
    itemRewards: {
      warrior: 'emberbound_leggings',
      mage: 'emberbound_leggings',
      rogue: 'emberbound_leggings',
    },
    requiresQuest: 'q_sw_offering',
    minLevel: 20,
    suggestedPlayers: 3,
  },
  q_sw_afterglow: {
    id: 'q_sw_afterglow',
    name: 'Water for the Living',
    giverNpcId: 'caravan_master_saffa',
    turnInNpcId: 'caravan_master_saffa',
    text: 'Haruk says the spring sings a note lower now, like a debt paid off. The Emberveil are ash or fled, the court is adjourned, and my ledger finally shows more water than worry. One last task, $N — walk the camp and let Maren, Caddis, and Brother Aldric each thank you properly. They have earned the chance, and so have you.',
    completionText:
      'Then it is done, and the Last Well is just... a well. First of many along a living road, if this old caravaneer has any say. The Scorching Wastes will remember your name, $N — the water remembers everything.',
    objectives: [
      {
        type: 'interact',
        targetNpcId: 'scout_maren_wastes',
        count: 1,
        label: 'Spoke with Scout Maren',
      },
      {
        type: 'interact',
        targetNpcId: 'loremaster_caddis_wastes',
        count: 1,
        label: 'Spoke with Loremaster Caddis',
      },
      {
        type: 'interact',
        targetNpcId: 'brother_aldric_wastes',
        count: 1,
        label: 'Spoke with Brother Aldric',
      },
    ],
    xpReward: 5000,
    copperReward: 3000,
    itemRewards: {},
    requiresQuest: 'q_sw_first_ember',
    minLevel: 20,
  },
};

export const SCORCHING_QUEST_ORDER: string[] = [
  'q_sw_arrival',
  'q_sw_prowlers',
  'q_sw_carrion_glass',
  'q_sw_lost_caravan',
  'q_sw_marauders',
  'q_sw_karesh',
  'q_sw_survey',
  'q_sw_vigil_dawn',
  'q_sw_vigil_noon',
  'q_sw_vigil_dusk',
  'q_sw_revenants',
  'q_sw_courtiers',
  'q_sw_braziers',
  'q_sw_sunspeaker',
  'q_sw_emberveil',
  'q_sw_writs',
  'q_sw_glasscut',
  'q_sw_offering',
  'q_sw_first_ember',
  'q_sw_afterglow',
];
