// Generate src/render/ability_vfx_specs.generated.ts from the gallery's
// ability_specs.js + ability_catalog.js (repo root). Vertical slice: only the
// classes in SLICE_CLASSES are emitted; everything else keeps the legacy VFX.
//   node scripts/vfx/gen_ingame_specs.mjs
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const SLICE_CLASSES = ['shaman'];

const { SPECS: specs } = await import(pathToFileURL('ability_specs.js'));
const { CATALOG: catalog } = await import(pathToFileURL('ability_catalog.js'));

const out = {};
const ids = [];
const auraNames = {};
for (const cls of SLICE_CLASSES) {
  for (const a of catalog[cls] ?? []) {
    ids.push(a.id);
    if (specs[a.id]) out[a.id] = specs[a.id];
    // sim `aura` events carry the English ability name; map it back to the id
    // so buff orbits can track the aura's real lifetime (gained → faded)
    if (a.name && specs[a.id]?.buff) auraNames[a.name] = a.id;
  }
}

let body = `// GENERATED by scripts/vfx/gen_ingame_specs.mjs — do not hand-edit.
// Per-ability VFX specs for the in-game slice (classes: ${SLICE_CLASSES.join(', ')}).
// Source of truth: /ability_specs.js + /ability_catalog.js (the gallery data).

export interface AbilityVfxSpec {
  archetype: string;
  palette?: string;
  power?: number;
  windup?: number;
  windupStyle?: string;
  linger?: number;
  self?: boolean;
  finisher?: boolean;
  accent?: string;
  hot?: number;
  tint?: string;
  rim?: string;
  decal?: string;
  motifs?: string[];
  motifAt?: string;
  shaft?: number | boolean;
  screenFx?: boolean;
  barrier?: boolean;
  bolt?: { speed?: number; jagged?: boolean; coils?: boolean; forkEvery?: number; volley?: number; tracer?: boolean; leader?: boolean; style?: string; headScale?: number };
  strike?: { arc?: string; swings?: number; bleed?: boolean; stars?: boolean; groundSlam?: boolean };
  nova?: { radius?: number };
  beam?: { dur?: number; ticks?: number; drain?: boolean };
  dot?: { drip?: string };
  cc?: { style?: string };
  shout?: { radius?: number; target?: boolean };
  burst?: { style?: string };
  buff?: { style?: string; orbit?: string; shellDur?: number; o?: Record<string, number | string> };
  impact?: Record<string, unknown>;
  spirit?: { model?: string; path?: string; at?: string; scale?: number; dur?: number; tint?: string; dim?: number } | null;
}

export const SLICE_ABILITY_IDS: ReadonlySet<string> = new Set(${JSON.stringify(ids)});

export const ABILITY_VFX_SPECS: Readonly<Record<string, AbilityVfxSpec>> = ${JSON.stringify(out, null, 1)};

// English aura name → slice ability id (buff-spec abilities only). Sim aura
// events name auras by ability name; sim output is locale-independent.
export const AURA_NAME_TO_ID: Readonly<Record<string, string>> = ${JSON.stringify(auraNames, null, 1)};
`;
writeFileSync('src/render/ability_vfx_specs.generated.ts', body);
console.log(`wrote src/render/ability_vfx_specs.generated.ts: ${Object.keys(out).length} specs, ${ids.length} slice ids`);
